spring:
  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
        input:
          destination: employee-details
          content-type: application/json
          group: group-1
          concurrency: 3
        output:
          destination: employee-details
          content-type: application/json
server:
  port: 8091
  servlet:
    context-path: /xeskafka-producer
